package mybatis.dao;

import java.util.List;
import mybatis.model.StudentUniClass;
import org.mybatis.cdi.Mapper;

@Mapper
public interface StudentUniClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_UNICLASS
     *
     * @mbg.generated Sun Apr 19 22:08:48 EEST 2020
     */
    int insert(StudentUniClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_UNICLASS
     *
     * @mbg.generated Sun Apr 19 22:08:48 EEST 2020
     */
    List<StudentUniClass> selectAll();
}