package mybatis.dao;

import java.util.List;
import mybatis.model.UniClass;
import org.mybatis.cdi.Mapper;

@Mapper
public interface UniClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNICLASS
     *
     * @mbg.generated Sun Apr 19 21:52:40 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNICLASS
     *
     * @mbg.generated Sun Apr 19 21:52:40 EEST 2020
     */
    int insert(UniClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNICLASS
     *
     * @mbg.generated Sun Apr 19 21:52:40 EEST 2020
     */
    UniClass selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNICLASS
     *
     * @mbg.generated Sun Apr 19 21:52:40 EEST 2020
     */
    List<UniClass> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.UNICLASS
     *
     * @mbg.generated Sun Apr 19 21:52:40 EEST 2020
     */
    int updateByPrimaryKey(UniClass record);
}