package mybatis.model;

public class StudentUniClass {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_UNICLASS.STUDENTS_ID
     *
     * @mbg.generated Sun Apr 19 22:08:48 EEST 2020
     */
    private Integer studentsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT_UNICLASS.UNICLASS_ID
     *
     * @mbg.generated Sun Apr 19 22:08:48 EEST 2020
     */
    private Integer uniclassId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_UNICLASS.STUDENTS_ID
     *
     * @return the value of PUBLIC.STUDENT_UNICLASS.STUDENTS_ID
     *
     * @mbg.generated Sun Apr 19 22:08:48 EEST 2020
     */
    public Integer getStudentsId() {
        return studentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_UNICLASS.STUDENTS_ID
     *
     * @param studentsId the value for PUBLIC.STUDENT_UNICLASS.STUDENTS_ID
     *
     * @mbg.generated Sun Apr 19 22:08:48 EEST 2020
     */
    public void setStudentsId(Integer studentsId) {
        this.studentsId = studentsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT_UNICLASS.UNICLASS_ID
     *
     * @return the value of PUBLIC.STUDENT_UNICLASS.UNICLASS_ID
     *
     * @mbg.generated Sun Apr 19 22:08:48 EEST 2020
     */
    public Integer getUniclassId() {
        return uniclassId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT_UNICLASS.UNICLASS_ID
     *
     * @param uniclassId the value for PUBLIC.STUDENT_UNICLASS.UNICLASS_ID
     *
     * @mbg.generated Sun Apr 19 22:08:48 EEST 2020
     */
    public void setUniclassId(Integer uniclassId) {
        this.uniclassId = uniclassId;
    }
}